### ISSUE TITLE
AttributeError: 'jittor_core.Var' object has no attribute 'sort'

### ISSUE THREAD

**Issue by YongZh958** [Jittor/JDet#10]
Wed Aug 25 15:01:57 2021 Validating....
  0%|                                                                                                                                                   | 33/41429 [01:43<36:05:37,  3.14s/it]
Traceback (most recent call last):
  File "tools/run_net.py", line 47, in <module>
    main()
  File "tools/run_net.py", line 40, in main
    runner.run()
  File "/root/ZY/JDet-master/python/jdet/runner/runner.py", line 85, in run
    self.val()
  File "/root/anaconda3/envs/Jit/lib/python3.7/site-packages/jittor/__init__.py", line 89, in inner
    ret = func(*args, **kw)
  File "/root/anaconda3/envs/Jit/lib/python3.7/site-packages/jittor/__init__.py", line 257, in inner
    ret = func(*args, **kw)
  File "/root/ZY/JDet-master/python/jdet/runner/runner.py", line 153, in val
    result = self.model(images,targets)
  File "/root/anaconda3/envs/Jit/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
    return self.execute(*args, **kw)
  File "/root/ZY/JDet-master/python/jdet/models/networks/s2anet.py", line 35, in execute
    outputs = self.bbox_head(features, targets)
  File "/root/anaconda3/envs/Jit/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
    return self.execute(*args, **kw)
  File "/root/ZY/JDet-master/python/jdet/models/roi_heads/s2anet_head.py", line 627, in execute
    return self.get_bboxes(*outs,self.parse_targets(targets,is_train=False))
  File "/root/ZY/JDet-master/python/jdet/models/roi_heads/s2anet_head.py", line 538, in get_bboxes
    scale_factor, cfg, rescale)
  File "/root/ZY/JDet-master/python/jdet/models/roi_heads/s2anet_head.py", line 597, in get_bboxes_single
    cfg.max_per_img)
  File "/root/ZY/JDet-master/python/jdet/ops/nms_rotated.py", line 589, in multiclass_nms_rotated
    _, inds = scores.sort(descending=True)
AttributeError: 'jittor_core.Var' object has no attribute 'sort'

训练了6小时左右出现这个错误

**Comment by li-xl** [comment]
python/jdet/ops/nms_rotated.py的589行改成`inds,_ = scores.argsort(descending=True)`就可以了，我已经更新了JDet，修复了这个问题，感谢支持！

**Comment by YongZh958** [comment]
[w 0825 16:15:52.108481 20 __init__.py:980] load parameter fc.weight failed ...
[w 0825 16:15:52.108591 20 __init__.py:980] load parameter fc.bias failed ...
[w 0825 16:15:52.108702 20 __init__.py:998] load total 267 params, 2 failed

[w 0825 16:16:02.075836 20 cudnn_conv_Tx:float32__Ty:float32__Tw:float32__XFORMAT:abcd__WFORMAT:oihw__YFORMAT:abcd__J...hash:798cb5ed49dadaa2_op.cc:200] forward_ algorithm cache is full
[w 0825 16:16:02.650392 20 cudnn_conv_backward_w_Tx:float32__Ty:float32__Tw:float32__XFORMAT:abcd__WFORMAT:oihw__YFOR...hash:c41e3d43aa5d4cf7_op.cc:199] backward w algorithm cache is full
[w 0825 16:16:04.062816 20 cudnn_conv_backward_x_Tx:float32__Ty:float32__Tw:float32__XFORMAT:abcd__WFORMAT:oihw__YFOR...hash:74f24b7a5fa4fe17_op.cc:201] backward x algorithm cache is full

请问在加载模型时，出现这些警告会影响模型的训练吗

**Comment by li-xl** [comment]
不会的，这是jittor在搜索最快的运行算法，只是搜索的缓存满了

**Comment by YongZh958** [comment]
好的，谢谢帮助
