### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by YongZh958** [Jittor/JDet#14]
Traceback (most recent call last):
  File "/root/anaconda3/envs/Jit/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/Jit/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/ZY/JDet-master/python/jdet/data/devkits/result_merge.py", line 230, in mergesingle
    nameboxnmsdict = nmsbynamedict(nameboxdict, nms, nms_threshold_0)
  File "/root/ZY/JDet-master/python/jdet/data/devkits/result_merge.py", line 171, in nmsbynamedict
    keep = nms(np.array(nameboxdict[imgname]), thresh)
  File "/root/ZY/JDet-master/python/jdet/data/devkits/result_merge.py", line 105, in py_cpu_nms_poly_fast
    iou = iou_poly(polys[i], polys[tmp_order[j]])
  File "/root/ZY/JDet-master/python/jdet/ops/nms_poly.py", line 310, in iou_poly
    iou = inter_area/(poly1.area+poly2.area-inter_area)
ZeroDivisionError: float division by zero

test时出现的报错

**Comment by li-xl** [comment]
您好，已修复，请pull最新版试一下

**Comment by YongZh958** [comment]
要重新从网站下载环境test吗

**Comment by li-xl** [comment]
可以把/root/ZY/JDet-master/python/jdet/ops/nms_poly.py的310行改成这个`iou = inter_area/max(poly1.area+poly2.area-inter_area,0.01)`，这样就不用下载啦，我只改了这一行代码

**Comment by YongZh958** [comment]
好的
