### ISSUE TITLE
python preprocess.py --config-file dota_preprocess_ config.py 报错

### ISSUE THREAD

**Issue by Kodapsy** [Jittor/JDet#2]
错误如下
Traceback (most recent call last):
  File "preprocess.py", line 4, in <module>
    from jdet.config import init_cfg, get_cfg
  File "/home/vr1/anaconda3/envs/env_ybgu/lib/python3.7/site-packages/jdet-0.1-py3.7.egg/jdet/__init__.py", line 1, in <module>
ImportError: cannot import name 'models' from 'jdet' (/home/vr1/anaconda3/envs/env_ybgu/lib/python3.7/site-packages/jdet-0.1-py3.7.egg/jdet/__init__.py)
搜索并未找到解决办法，还请作者指点。

**Comment by li-xl** [comment]
请问你有试过通过设置pythonpath的方式吗？PYTHONPATH=/home/your_own_path/JDet/python python3 preprocess.py ...

**Comment by Kodapsy** [comment]
您好，感谢您的回复，我之前试过这种绝对路径的方法，和我进入这个文件夹下运行命令是一样的结果，都会报这个错误。

**Comment by Kodapsy** [comment]
> 请问你有试过通过设置pythonpath的方式吗？PYTHONPATH=/home/your_own_path/JDet/python python3 preprocess.py ...

您好，感谢您的回复，我之前试过这种绝对路径的方法，和我进入这个文件夹下运行命令是一样的结果，都会报这个错误。

**Comment by li-xl** [comment]
您好，我用conda试了一下，python setup.py install 确实会报这个错误，我们修复一下，您可以用python setup.py develop来安装，这个是没有问题的

**Comment by li-xl** [comment]
您好，我修好了，更新一下jdet就可以用啦，感谢！

**Comment by Kodapsy** [comment]
好的，感谢您的工作! ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月5日(星期四) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jittor/JDet] python preprocess.py --config-file dota_preprocess_ config.py 报错 (#2)

**Comment by Kodapsy** [comment]
> 您好，我修好了，更新一下jdet就可以用啦，感谢！

我更新之后又报错
  File "preprocess.py", line 10
    os.system(f"rm -rf {os.path.join(cfg.source_dataset_path, 'trainval')}")
                                                                          ^
SyntaxError: invalid syntax
![image](https://user-images.githubusercontent.com/87477193/128470660-adfabed5-409d-43d3-be74-900f3fad954e.png)
找了好久没找到问题在哪。。明明没有语法错误。。

**Comment by cxjyxxme** [comment]
这确实有点奇怪，我们这里测试是没有问题的，请问您修改过这个文件吗？是不是有什么不可见的符号，或者缩进的问题？或者您的python版本不支持fstring，您的版本应该是python3.7吧？

**Comment by Kodapsy** [comment]
> 这确实有点奇怪，我们这里测试是没有问题的，请问您修改过这个文件吗？是不是有什么不可见的符号，或者缩进的问题？或者您的python版本不支持fstring，您的版本应该是python3.7吧？

我的python版本是3.7 我为了排除修改过的问题 重新下载了您的代码 还是报一样的错误。。

**Comment by li-xl** [comment]
那您方便把报错的代码，打包发给我吗？我的邮箱：lixl19@mails.tsinghua.edu.cn

**Comment by Kodapsy** [comment]
> 那您方便把报错的代码，打包发给我吗？我的邮箱：[lixl19@mails.tsinghua.edu.cn](mailto:lixl19@mails.tsinghua.edu.cn)

好的，麻烦您了。

**Comment by li-xl** [comment]
您好，我试了下您的代码，我这边跑是没有什么问题的？要把您把这个函数注释掉试试？或者把路径改成英文试试？

**Comment by li-xl** [comment]
如果还是不行的话，我可以远程帮你看一下。

**Comment by Kodapsy** [comment]
> 如果还是不行的话，我可以远程帮你看一下。

非常感谢您的耐心解答！我已经解决了，我把os.system(f"")中的f删掉就不报错了。再次感谢！

**Comment by bangbox2** [comment]
> > 请问你有试过通过设置pythonpath的方式吗？PYTHONPATH=/home/your_own_path/JDet/python python3 preprocess.py ...
> 
> 您好，感谢您的回复，我之前试过这种绝对路径的方法，和我进入这个文件夹下运行命令是一样的结果，都会

> 您好，我修好了，更新一下jdet就可以用啦，感谢！

你好，我也遇到了这个问题，请问怎么更新

**Comment by Kodapsy** [comment]
你好，如果你下载代码用的是git clone的方式，再用一遍命令即可，具体可以搜一下用法，如果你是从github下载的zip解压的方式，可以重新下载项目，步骤从头开始再来一遍。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jittor/JDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月9日(星期一) 上午10:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jittor/JDet] python preprocess.py --config-file dota_preprocess_ config.py 报错 (#2)





   
请问你有试过通过设置pythonpath的方式吗？PYTHONPATH=/home/your_own_path/JDet/python python3 preprocess.py ...
  
您好，感谢您的回复，我之前试过这种绝对路径的方法，和我进入这个文件夹下运行命令是一样的结果，都会
   
您好，我修好了，更新一下jdet就可以用啦，感谢！
  
你好，我也遇到了这个问题，请问怎么更新
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bangbox2** [comment]
> 你好，如果你下载代码用的是git clone的方式，再用一遍命令即可，具体可以搜一下用法，如果你是从github下载的zip解压的方式，可以重新下载项目，步骤从头开始再来一遍。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jittor/JDet" ***@***.***&gt;; 发送时间:&nbsp;2021年8月9日(星期一) 上午10:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Jittor/JDet] python preprocess.py --config-file dota_preprocess_ config.py 报错 (#2) 请问你有试过通过设置pythonpath的方式吗？PYTHONPATH=/home/your_own_path/JDet/python python3 preprocess.py ... 您好，感谢您的回复，我之前试过这种绝对路径的方法，和我进入这个文件夹下运行命令是一样的结果，都会 您好，我修好了，更新一下jdet就可以用啦，感谢！ 你好，我也遇到了这个问题，请问怎么更新 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

更新了好像也不行

**Comment by cxjyxxme** [comment]
您先python -m pip uninstall jdet卸载jdet，然后可以通过import jdet测试一下是否卸载干净了，卸载干净后，您再下载最新版jdet然后安装试一下？
