### ISSUE TITLE
无法开始训练

### ISSUE THREAD

**Issue by liuyanyi** [Jittor/JDet#3]
运行训练代码时出现了如下错误
```
Traceback (most recent call last):
  File "tools/run_net.py", line 47, in <module>
    main()
  File "tools/run_net.py", line 40, in main
    runner.run()
  File "/workspace/JDet/python/jdet/runner/runner.py", line 81, in run
    self.train()
  File "/workspace/JDet/python/jdet/runner/runner.py", line 101, in train
    batch_size = len(targets)**jt.mpi.world_size()
AttributeError: 'NoneType' object has no attribute 'world_size'
```

根据Jittor官网上的说明，jt.mpi在没有mpi环境时是None，那么单卡环境下如何运行JDet呢

**Comment by li-xl** [comment]
可以先把*jt.mpi.world_size()，改成*1,应该是没有装好mpi导致jt.mpi是None，我们稍后会更新一下jittor，感谢反馈！

**Comment by li-xl** [comment]
同学你好，现在已经可以用了，更新下jittor和jdet即可。

**Comment by liuyanyi** [comment]
感谢您的回复，现在已经可以开始训练了

**Comment by Kodapsy** [comment]
> 同学你好，现在已经可以用了，更新下jittor和jdet即可。

![image](https://user-images.githubusercontent.com/87477193/128586055-7d8b3436-faaa-4c99-968b-5f87eacab2e9.png)
您好，我更新了之后还是有同样的问题。。

**Comment by li-xl** [comment]
可以用git clone的方式更新一下jittor，或者直接把jt.world_size替换为1就可以了











祝好

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月7日(周六) 中午11:11
收件人: ***@***.***&gt;;
抄送: "Xiang-Li ***@***.******@***.***&gt;;
主题: Re: [Jittor/JDet] 无法开始训练 (#3)




  
同学你好，现在已经可以用了，更新下jittor和jdet即可。
  

 您好，我更新了之后还是有同样的问题。。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kodapsy** [comment]
> 可以用git clone的方式更新一下jittor，或者直接把jt.world_size替换为1就可以了 祝好
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月7日(周六) 中午11:11 收件人: ***@***.***&gt;; 抄送: "Xiang-Li ***@***.******@***.***&gt;; 主题: Re: [Jittor/JDet] 无法开始训练 (#3) 同学你好，现在已经可以用了，更新下jittor和jdet即可。 您好，我更新了之后还是有同样的问题。。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

感谢回复，我替换成1可以了。

**Comment by bangbox2** [comment]
> 感谢您的回复，现在已经可以开始训练了

你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差

**Comment by cxjyxxme** [comment]
> 
> 
> > 感谢您的回复，现在已经可以开始训练了
> 
> 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差

您训练的是哪个模型呢，用的什么脚本呢？

**Comment by liuyanyi** [comment]
> > 感谢您的回复，现在已经可以开始训练了
> 
> 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差

我训练的是s2anet，精度上和readme里给的差不太多

**Comment by li-xl** [comment]
请问，config是哪个，有修改吗？











祝好

---原始邮件---
发件人: "Yanyi ***@***.***&gt;
发送时间: 2021年8月12日(周四) 中午11:57
收件人: ***@***.***&gt;;
抄送: "Xiang-Li ***@***.******@***.***&gt;;
主题: Re: [Jittor/JDet] 无法开始训练 (#3)




   
感谢您的回复，现在已经可以开始训练了
  
你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差
  
我训练的是s2anet，精度上和readme里给的差不太多
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuyanyi** [comment]
> 请问，config是哪个，有修改吗？ 祝好
> […](#)
> ---原始邮件--- 发件人: "Yanyi ***@***.***&gt; 发送时间: 2021年8月12日(周四) 中午11:57 收件人: ***@***.***&gt;; 抄送: "Xiang-Li ***@***.******@***.***&gt;; 主题: Re: [Jittor/JDet] 无法开始训练 (#3) 感谢您的回复，现在已经可以开始训练了 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差 我训练的是s2anet，精度上和readme里给的差不太多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我用的是这个config
[config](https://github.com/Jittor/JDet/blob/master/projects/s2anet/configs/s2anet_r50_fpn_1x_dota.py)
应该只修改了数据集的位置，去掉了最后的pretrained_weights

**Comment by bangbox2** [comment]
> > > 感谢您的回复，现在已经可以开始训练了
> > 
> > 
> > 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差
> 
> 您训练的是哪个模型呢，用的什么脚本呢？


> > > 感谢您的回复，现在已经可以开始训练了
> > 
> > 
> > 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差
> 
> 您训练的是哪个模型呢，用的什么脚本呢？

Duplicate of #

> 请问，config是哪个，有修改吗？ 祝好
> […](#)
> ---原始邮件--- 发件人: "Yanyi ***@***.***&gt; 发送时间: 2021年8月12日(周四) 中午11:57 收件人: ***@***.***&gt;; 抄送: "Xiang-Li ***@***.******@***.***&gt;; 主题: Re: [Jittor/JDet] 无法开始训练 (#3) 感谢您的回复，现在已经可以开始训练了 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差 我训练的是s2anet，精度上和readme里给的差不太多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

直接用你给的这个训练的
python tools/run_net.py --config-file=configs/s2anet_r50_fpn_1x_dota.py --task=train
代码没有修改，但是提交上去的mAP只有0.00

> 请问，config是哪个，有修改吗？ 祝好
> […](#)
> ---原始邮件--- 发件人: "Yanyi ***@***.***&gt; 发送时间: 2021年8月12日(周四) 中午11:57 收件人: ***@***.***&gt;; 抄送: "Xiang-Li ***@***.******@***.***&gt;; 主题: Re: [Jittor/JDet] 无法开始训练 (#3) 感谢您的回复，现在已经可以开始训练了 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差 我训练的是s2anet，精度上和readme里给的差不太多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

python tools/run_net.py --config-file=configs/s2anet_r50_fpn_1x_dota.py --task=train
我直接用这个运行的，修改了配置文件数据集的位置，mAP为0.01

**Comment by bangbox2** [comment]
> 请问，config是哪个，有修改吗？ 祝好
> […](#)
> ---原始邮件--- 发件人: "Yanyi ***@***.***&gt; 发送时间: 2021年8月12日(周四) 中午11:57 收件人: ***@***.***&gt;; 抄送: "Xiang-Li ***@***.******@***.***&gt;; 主题: Re: [Jittor/JDet] 无法开始训练 (#3) 感谢您的回复，现在已经可以开始训练了 你好，我想请问下你的训练结果怎么样，我在dota数据集上提交的结果很差 我训练的是s2anet，精度上和readme里给的差不太多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

直接用下面这个训练的
python tools/run_net.py --config-file=configs/s2anet_r50_fpn_1x_dota.py --task=train
之修改了数据集的位置，mAP只有0.01

**Comment by li-xl** [comment]
那应该没问题，我训过几次都没问题。您方便加群761222083交流，或者把代码发给我我看一下吗，我邮箱：lixl19@mails.tsinghua.edu.cn

**Comment by li-xl** [comment]
您好,我觉得mAP这么低可能是图片尺寸的问题,我把s2anet的get_bboxes,rescale默认改成True了,您再试一下?

**Comment by HeuristicLU** [comment]
您好，我遇到些问题，想请教下
我的配置文件type='DOTA1_5'
source_dataset_path='/media/asus/299D817A2D97AD94/ok_PROJs/JDet/datasets/DOTA1_5/'
target_dataset_path='/media/asus/299D817A2D97AD94/ok_PROJs/JDet/datasets/processed_DOTA1_5/'
路径没有错误，DOTA1_5下面是挑选出来的部分数据，我在其他程序上测过，没有问题。

运行数据处理，报错：
(sky) asus@asus-System-Product-Name:/media/asus/299D817A2D97AD94/ok_PROJs/JDet$ python tools/preprocess.py --config-file configs/preprocess/dota1_5_preprocess_config.py 
[i 1118 17:31:28.681917 08 compiler.py:944] Jittor(1.3.1.18) src: /home/asus/anaconda3/envs/sky/lib/python3.7/site-packages/jittor
[i 1118 17:31:28.689649 08 compiler.py:945] g++ at /usr/bin/g++(7.5.0)
[i 1118 17:31:28.689716 08 compiler.py:946] cache_path: /home/asus/.cache/jittor/jt1.3.1/g++7.5.0/py3.7.9/Linux-5.4.0-89xd6/AMDRyzen93950Xxea/default
[i 1118 17:31:28.697931 08 __init__.py:372] Found nvcc(10.1.105) at /usr/local/cuda-10.1/bin/nvcc.
[i 1118 17:31:28.754584 08 __init__.py:372] Found gdb(8.1.0) at /usr/bin/gdb.
[i 1118 17:31:28.763441 08 __init__.py:372] Found addr2line(2.30) at /usr/bin/addr2line.
[i 1118 17:31:28.866922 08 compiler.py:997] cuda key:cu10.1.105_sm_75
[i 1118 17:31:29.054781 08 __init__.py:187] Total mem: 62.79GB, using 16 procs for compiling.
[i 1118 17:31:29.114659 08 jit_compiler.cc:27] Load cc_path: /usr/bin/g++
[i 1118 17:31:29.215793 08 init.cc:61] Found cuda archs: [75,]
[i 1118 17:31:29.230639 08 compile_extern.py:497] mpicc not found, distribution disabled.
[i 1118 17:31:29.271848 08 compile_extern.py:29] found /usr/local/cuda-10.1/include/cublas.h
[i 1118 17:31:29.283580 08 compile_extern.py:29] found /usr/lib/x86_64-linux-gnu/libcublas.so
[i 1118 17:31:29.283738 08 compile_extern.py:29] found /usr/lib/x86_64-linux-gnu/libcublasLt.so.10
[i 1118 17:31:29.420154 08 compile_extern.py:29] found /usr/local/cuda-10.1/include/cudnn.h
[i 1118 17:31:29.437553 08 compile_extern.py:29] found /usr/local/cuda-10.1/lib64/libcudnn.so
[i 1118 17:31:30.539454 08 compile_extern.py:29] found /usr/local/cuda-10.1/include/curand.h
[i 1118 17:31:30.572073 08 compile_extern.py:29] found /usr/local/cuda-10.1/lib64/libcurand.so
munmap_chunk(): invalid pointer
已放弃 (核心已转储)
(sky) asus@asus-System-Product-Name:/media/asus/299D817A2D97AD94/ok_PROJs/JDet$ python -V
Python 3.7.9
