### ISSUE TITLE
cuda问题

### ISSUE THREAD

**Issue by liliwannian** [Jittor/JDet#39]
你好，我的cuda版本为10.2，在执行python tools/run_net.py --config-file=configs/s2anet/s2anet_r18_fpn_1x_kaggle_rotate_ms.py --task=train后出现以下问题：
```
Traceback (most recent call last):
  File "tools/run_net.py", line 56, in <module>
    main()
  File "tools/run_net.py", line 46, in main
    runner.run()
  File "/home/xx/xx/s2a/JDet-s2a/python/jdet/runner/runner.py", line 87, in run
    self.train()
  File "/home/xx/xx/s2a/JDet-s2a/python/jdet/runner/runner.py", line 133, in train
    if all_loss > 10:
  File "/home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py", line 1427, in to_bool
    return ori_bool(v.item())
RuntimeError: [f 1214 20:38:47.244717 36 executor.cc:584] 
Execute fused operator(1199/1444) failed. 
[JIT Source]: /home/xx/.cache/jittor/jt1.3.1/g++7.5.0/py3.7.11/Linux-4.15.0-1x19/IntelRXeonRSilxb7/default/cu11.2.152_sm_75/jit/_opkey0_broadcast_to_Tx_float32__DIM_3__BCAST_1__JIT_1__JIT_cuda_1__index_t_int32___opkey1___hash_7c8decc46b39eb60_op.cc 
[OP TYPE]: fused_op:( broadcast_to, broadcast_to, binary.multiply, reduce.add,)
[Input]: float32[2304,128,], float32[256,2304,], 
[Output]: float32[256,128,], 
[Async Backtrace]: --- 
     tools/run_net.py:56 <<module>> 
     tools/run_net.py:46 <main> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/runner/runner.py:87 <run> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/runner/runner.py:131 <train> 
     /home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py:776 <__call__> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/models/networks/s2anet.py:35 <execute> 
     /home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py:776 <__call__> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/models/roi_heads/s2anet_head.py:625 <execute> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/utils/general.py:52 <multi_apply> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/models/roi_heads/s2anet_head.py:236 <forward_single> 
     /home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py:776 <__call__> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/models/roi_heads/s2anet_head.py:722 <execute> 
     /home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py:776 <__call__> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/ops/dcn_v1.py:696 <execute> 
     /home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py:1296 <apply> 
     /home/xx/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/__init__.py:1252 <__call__> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/ops/dcn_v1.py:598 <execute> 
     /home/xx/xx/s2a/JDet-s2a/python/jdet/ops/dcn_v1.py:447 <deform_conv_forward_cuda> 
     /home/x/anaconda3/envs/jdet2/lib/python3.7/site-packages/jittor/nn.py:151 <matmul> 
[Reason]: [f 1214 20:38:47.244082 36 helper_cuda.h:126] CUDA error at /home/xx/.cache/jittor/jt1.3.1/g++7.5.0/py3.7.11/Linux-4.15.0-1x19/IntelRXeonRSilxb7/default/cu11.2.152_sm_75/jit/cublas_matmul_T_float32__Trans_a_N__Trans_b_N__op_S__JIT_1__JIT_cuda_1__index_t_int32__hash_bde4b1ed93632c6c_op.cc:51  code=7( CUBLAS_STATUS_INVALID_VALUE ) cublasSgemm(handle_, CUBLAS_OP_N, CUBLAS_OP_N, k, n, m, &alpha, b->ptr<T>(), 'N' == 'N' ? k : m, a->ptr<T>(), 'N' == 'N' ? m : n, &beta, c->ptr<T>(), k)
```
请问一个如何解决？谢谢。

**Comment by li-xl** [comment]
方便贴一下config文件看一下吗？

**Comment by YbugY** [comment]
请问最后是怎么解决的
