### ISSUE TITLE
About code (rpn losses)

### ISSUE THREAD

**Issue by Artcs1** [Jittor/JDet#89]
Hello, great work!!. I run the code with the faster CNN config after preprocessing the DOTA dataset. Starting the training I got the next error.

```
[i 0726 20:47:53.981310 28 compiler.py:955] Jittor(1.3.6.3) src: /home/jeffri/anaconda3/envs/JDet/lib/python3.9/site-packages/jittor
[i 0726 20:47:53.982849 28 compiler.py:956] g++ at /usr/bin/g++(9.4.0)
[i 0726 20:47:53.982878 28 compiler.py:957] cache_path: /home/jeffri/Desktop/JDet-cobb/build/.cache/jittor/jt1.3.6/g++9.4.0/py3.9.19/Linux-5.15.0-1x1c/12thGenIntelRCxd8/default
[i 0726 20:47:54.032117 28 install_cuda.py:93] cuda_driver_version: [12, 4]
[i 0726 20:47:54.034004 28 __init__.py:411] Found /home/jeffri/Desktop/JDet-cobb/build/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc(11.2.152) at /home/jeffri/Desktop/JDet-cobb/build/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc.
[i 0726 20:47:54.060767 28 __init__.py:411] Found gdb(20.04.2) at /usr/bin/gdb.

[i 0726 20:47:54.062583 28 __init__.py:411] Found addr2line(2.34) at /usr/bin/addr2line.
[i 0726 20:47:54.109160 28 compiler.py:1010] cuda key:cu11.2.152_sm_86
[i 0726 20:47:54.183567 28 __init__.py:227] Total mem: 62.60GB, using 16 procs for compiling.
[i 0726 20:47:54.232542 28 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0726 20:47:54.289894 28 init.cc:62] Found cuda archs: [86,]
[i 0726 20:47:54.339520 28 compile_extern.py:519] mpicc not found, distribution disabled.
[i 0726 20:47:55.742823 28 cuda_flags.cc:39] CUDA enabled.
Loading config from:  configs/faster_rcnn/faster_rcnn_obb_r50_fpn_1x_dota.py
[w 0726 20:47:55.922384 28 __init__.py:1507] load parameter fc.weight failed ...
[w 0726 20:47:55.922456 28 __init__.py:1507] load parameter fc.bias failed ...
[w 0726 20:47:55.923076 28 __init__.py:1526] load total 267 params, 2 failed
Fri Jul 26 20:47:56 2024 Start running

Compiling Operators(3/3) used: 2.31s eta:    0s 
Traceback (most recent call last):
  File "/home/jeffri/Desktop/JDet-cobb/tools/run_net.py", line 64, in <module>
    main()
  File "/home/jeffri/Desktop/JDet-cobb/tools/run_net.py", line 55, in main
    runner.run()
  File "/home/jeffri/Desktop/JDet-cobb/python/jdet/runner/runner.py", line 84, in run
    self.train()
  File "/home/jeffri/Desktop/JDet-cobb/python/jdet/runner/runner.py", line 125, in train
    losses = self.model(images,targets)
  File "/home/jeffri/anaconda3/envs/JDet/lib/python3.9/site-packages/jittor/__init__.py", line 1109, in __call__
    return self.execute(*args, **kw)
  File "/home/jeffri/Desktop/JDet-cobb/python/jdet/models/networks/faster_rcnn_obb.py", line 192, in execute
    for k, v in rpn_losses.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Any intuition of what is happening??

**Comment by OrangeSodahub** [comment]
It means that your `rpn_losses` is `None`
